#!/usr/bin/env bash

echo "Vim wrapper for opening files using compiler output"

usage()
{
    echo "Usage: `basename $0` path/to/file:linenumber"
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

readonly file=${1%%:*}
readonly linenumber=${1##*:}

vim $file +$linenumber
