#!/bin/bash -e
#
# darwin		This init.d script is used to start darwin.
#			It starts both the server and the web interface.
#
# Copyright (c) 2012, Jochen Issing <iss@nesono.com>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ENV="env -i LANG=C PATH=/usr/local/bin:/usr/bin:/bin"

set -e

DARWINSS="/usr/local/sbin/DarwinStreamingServer"
SADMINS="/usr/local/sbin/streamingadminserver.pl"

if [ -x $DARWINSS ] ; then
	HAVE_DARWIN=1
else
	exit 0
fi
if [ -x $SADMINS ] ; then
	HAVE_SADMINS=1
else
	exit 0
fi

. /lib/lsb/init-functions

test -f /etc/default/rcS && . /etc/default/rcS

stop_servers() 
{
  # kill server admin
  SADMINPIDS=`ps ax | grep $SADMINS | grep -v grep | awk '{print $1;}'`
  DARWINPIDS=`pidof $DARWINSS`

  ALLPIDS="$SADMINPIDS $DARWINPIDS"
  if [ "$ALLPIDS" != " " ]; then
    kill $ALLPIDS
  fi

  sleep 2

  # check if instances still running
  if [ -n "`ps ax | grep $SADMINS | grep -v grep | awk '{print $1;}'`" ]; then
    echo "administration interface still running"
    return -1
  fi
  # check if instances still running
  if [ -n "`pidof $DARWINSS`" ]; then
    echo "Darwin Streaming Server still running"
    return -1
  fi

  return 0
}

start_servers() 
{
  # start darwin
  $DARWINSS
  # check return value
  if [ $? != 0 ]; then
    return -1
  fi
  # start server admin server
  $SADMINS
  # check return value
  if [ $? != 0 ]; then
    return -1
  fi

  return 0
}

# the calling cases
case $1 in
	start)
		log_begin_msg "Starting Darwin Streaming Server web server..."
		if start_servers; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	stop)
		log_begin_msg "Stopping Darwin Streaming Server web server..."
		if stop_servers; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	restart)
		log_begin_msg "Restarting Darwin Streaming Server web server..."
		if ! stop_servers; then
                        log_end_msg 1
                fi
		if start_servers; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	status)
		exit 4
	;;
	*)
		echo "Usage: /etc/init.d/darwin start|stop|restart" >&2
		exit 2
	;;
esac
