#!/usr/bin/env bash
# script to install the nesono-bin package, which
# is a set of useful scripts not only for nesono groups developments
#
# Copyright (c) 2012, Jochen Issing <iss@nesono.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

echo ""
echo "                         INSTALL nesono-bin"
echo "script to install the nesono-bin directory into newly setup or existing systems"
echo "checks, if already in path and if config files have already been set"
echo "so don't be afraid, to call this script multiple times :-)"
echo ""
echo "the script is licensed under BSD license - read it's source for more information"
echo ""
echo "results:"

# not used currently
FORCE=0

# function to install a link to a configuration file, e.g. ~/.vimrc
function install_link()
{
  DST=${1}
  SRC=${2}

  # check for bogus links - otherwise confusing existence check
  if [ -L "${DST}" ]; then
    # get target from link
    linktarget=$(readlink "${DST}")
    dirname=$(dirname "${DST}")

    if [ -n "${linktarget##/*}" ]; then
      # relative target found
      target=${dirname}/${linktarget}
    else
      # absolute target found
      target=${linktarget}
    fi

    if [ ! -e "${target}" ]; then
      echo "removing bogus link: \"${DST}\" pointing to \"${target}\""
      rm "${DST}"
    fi
  fi
  if [ -e ${DST} ]; then
    echo "---> ${DST} exists - not overwriting with nesono-bin version"
    if [ -L ${DST} ]; then
      TESTDST=`readlink ${DST}`
      echo "     ${DST} points to ${TESTDST}"
      echo ""
    fi
  else
    echo "installing ${DST##*/}"
    ln -sf ${SRC} ${DST}
  fi
}

# check for -f or --force
case ${1} in
  '--force' | 'f')
    FORCE=1
    echo "##### force mode active"
  ;;
esac

pushd ~/nesono-bin
./bashtils/install_nesono_bash
./zshtils/install_nesono_zsh
popd

install_link ~/.inputrc    ~/nesono-bin/inputrc
install_link ~/.vimrc      ~/nesono-bin/vimrc
install_link ~/.tmux.conf  ~/nesono-bin/tmux.conf
install_link ~/.screenrc   ~/nesono-bin/screenrc
install_link ~/.tigrc      ~/nesono-bin/tigrc

echo "fetch zsh-syntax-highlighting"
pushd ~/nesono-bin
git submodule init zsh-syntax-highlighting
git submodule update zsh-syntax-highlighting
popd

echo ""
exit 0
