#!/bin/bash
# script to install the nesono-bin package, which
# is a set of useful scripts not only for nesono groups developments

echo ""
echo "                         INSTALL nesono-bin"
echo "script to install the nesono-bin directory into newly setup or existing systems"
echo "checks, if already in path and if config files have already been set"
echo "so don't be afraid, to call this script multiple times :-)"
echo ""
echo "Results:"

# function to install a link to a configuration file, e.g. ~/.vimrc
function install_link()
{
  DST=${1}
  SRC=${2}

  if [ -e ${DST} ]; then
    echo "---> ${DST} exists - not overwriting with nesono-bin version"
    if [ -L ${DST} ]; then
      TESTDST=`readlink ${DST}`
      echo "     ${DST} points to ${TESTDST}"
      echo ""
    fi
  else
    echo "installing ${DST##*/}"
    ln -sf ${SRC} ${DST}
  fi
}

pushd ~/nesono-bin
./bashtils/install_nesono_bash
./zshtils/install_nesono_zsh
popd

install_link ~/.inputrc          ~/nesono-bin/inputrc
install_link ~/.vimrc            ~/nesono-bin/vimrc
install_link ~/.screenrc         ~/nesono-bin/screenrc

echo ""
exit 0
