#!/usr/bin/env bash

[[ -x `which ctags 2> /dev/null`  ]] && ctags -R --sort=yes --c++-kinds=+p --fields=+afiKlmnsSzt --extra=+q && echo "ctags finished" &
[[ -x `which gtags 2> /dev/null`  ]] && gtags && echo "gtags finished" &
[[ -x `which cscope 2> /dev/null` ]] && cscope && echo "cscope finished" &
