#!/usr/bin/env bash
# convenience script for oprofile to avoid typing in all the commands
#
# Copyright (c) 2012, Jochen Issing <iss@nesono.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

sudo opcontrol --shutdown
sudo opcontrol --reset

# get application name - check for sudo
if [ ${1} == "sudo" ]; then
  PROF_APP_NAME=${2}
else
  PROF_APP_NAME=${1}
fi

echo "application under test: ${PROF_APP_NAME}"
echo ""

# using default event counter for now
sudo opcontrol --setup --no-vmlinux --event="default" --separate=library --callgraph=5
# used to use those for some time :: you can try and see what happens, if you like :)
#sudo opcontrol --setup --no-vmlinux --event=CPU_CLK_UNHALTED:4500:0:1:1 --separate=library --callgraph=5
#sudo opcontrol --setup --no-vmlinux --separate=library --callgraph=5

sudo opcontrol --start
$@
sudo opcontrol --shutdown

opreport "${PROF_APP_NAME}" -a --symbols="${PROF_APP_NAME}" --demangle=smart
#opreport "${PROF_APP_NAME}" -a --symbols="${PROF_APP_NAME}" --demangle=smart --callgraph
