[theme]
name = "plain"
[icons]
name = "material"

[theme.overrides]
# taken from here: https://fonts.google.com/icons?selected=Material+Icons
separator = "\ue5d4"

[icons.overrides]
xrandr = ""

[[block]]
block = "cpu"
#format = "{barchart} {utilization} {frequency}"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MUp} %"
#format_mem = "{mem_total_used_percents}"
format_swap = "{SUp}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "nvidia_gpu"
label = ""
show_memory = false
show_clocks = false
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "pacman"
interval = 600
format = "{pacman} "
format_singular = "{pacman} "
format_up_to_date = ""
critical_updates_regex = "(linux |linux-lts|linux-zen)"
#hide_when_uptodate = True

[[block]]
block = "xrandr"
icons = false
resolution = false
interval = 2

#[[block]]
#block = "pomodoro"
#length = 25
#break_length = 5
#message = "Take a break!"
#break_message = "Back to work!"
#use_nag = true
#nag_path = "i3-nagbar"

#[[block]]
#block = "music"
#player = "spotify"
#buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %Y-%m-%d %R"
