# Material from NerdFont
# https://www.nerdfonts.com/cheat-sheet
backlight_empty = "\ue38d" # nf-weather-moon_new
backlight_full = "\ue39b" # nf-weather-moon_full
backlight_1 = "\ue3d4" # nf-weather-moon_alt_waxing_gibbous_6
backlight_2 = "\ue3d3" # nf-weather-moon_alt_waxing_gibbous_5
backlight_3 = "\ue3d2" # nf-weather-moon_alt_waxing_gibbous_4
backlight_4 = "\ue3d1" # nf-weather-moon_alt_waxing_gibbous_3
backlight_5 = "\ue3d0" # nf-weather-moon_alt_waxing_gibbous_2
backlight_6 = "\ue3cf" # nf-weather-moon_alt_waxing_gibbous_1
backlight_7 = "\ue3ce" # nf-weather-moon_alt_first_quarter
backlight_8 = "\ue3cd" # nf-weather-moon_alt_waxing_crescent_6
backlight_9 = "\ue3cc" # nf-weather-moon_alt_waxing_crescent_5
backlight_10 = "\ue3cb" # nf-weather-moon_alt_waxing_crescent_4
backlight_11 = "\ue3ca" # nf-weather-moon_alt_waxing_crescent_3
backlight_12 = "\ue3c9" # nf-weather-moon_alt_waxing_crescent_2
backlight_13 = "\ue3c8" # nf-weather-moon_alt_waxing_crescent_1
bat_charging = "\uf583" # nf-mdi-battery_charging
bat_discharging = "\uf57d" # nf-mdi-battery_50
bat_empty = "\uf58d" # nf-mdi-battery_outline
bat_full = "\uf578" # nf-mdi-battery
bat_half = "\uf57d" # nf-mdi-battery_50
bat_quarter = "\uf57a"# nf-mdi-battery_20
bat_three_quarters = "\uf57f" # nf-mdi-battery_70
bell = "\uf599" # nf-mdi-bell
bell-slash = "\uf59a" # nf-mdi-bell_off
bluetooth = "\uf5ae" # nf-mdi-bluetooth
calendar = "\uf5ec" # nf-mdi-calendar
cogs = "\uf992" # nf-mdi-settings
cpu = "\uf9c4" # nf-mdi-speedometer
disk_drive = "\uf7c9" # nf-mdi-harddisk
docker = "\uf308" # nf-linux-docker
github = "\uf7a3" # nf-mdi-github_circle
gpu = "\uf878" # nf-mdi-monitor
headphones = "\uf7ca" # nf-mdi-headphones
joystick = "\uf796" # nf-mdi-gamepad_variant
keyboard = "\uf80b" # nf-mdi-keyboard
mail = "\uf6ed" # nf-mdi-email
memory_mem = "\uf85a" # nf-mdi-memory
memory_swap = "\uf7c9" # nf-mdi-harddisk
mouse = "\uf87c" # nf-mdi-mouse
music = "\uf886" # nf-mdi-music_note
music_next = "\uf9ac" # nf-mdi-skip_next
music_pause = "\uf8e3" # nf-mdi-pause
music_play = "\uf909" # nf-mdi-play
music_prev = "\uf9ad" # nf-mdi-skip_previous
net_bridge = "\uf9a9" # nf-mdi-sitemap
net_down = "\uf6d9" # nf-mdi-download
net_loopback = "\ufbe9" # nf-mdi-loop
net_modem = "\uf8f1" # nf-mdi-phone
net_up = "\ufa51" # nf-mdi-upload
net_vpn = "\ufa81" # nf-mdi-vpn
net_wired = "\uf6ff" # nf-mdi-ethernet
net_wireless = "\ufaa8" # nf-mdi-wifi
notification = "\uf599" # nf-mdi-bell
phone = "\uf8f1" # nf-mdi-phone
phone_disconnected = "\ufb57" # nf-mdi-phone_minus
ping = "\ufa1e" # nf-mdi-timer_sand
pomodoro = "\ue001" # nf-pom-pomodoro_done
resolution = "\uf792" # nf-mdi-fullscreen
tasks = "\ufac6" # nf-mdi-playlist_check
thermometer = "\ufa0e" # nf-mdi-thermometer
time = "\uf64f" # nf-mdi-clock
toggle_off = "\ufa21" # nf-mdi-toggle_switch_off
toggle_on = "\ufa20" # nf-mdi-toggle_switch
unknown = "\uf685" # nf-mdi-comment_question_outline | TODO: Make default?
update = "\ufbae" # nf-mdi-update
uptime = "\uf652" # nf-mdi-clock_in
volume_empty = "\ufa7e" # nf-mdi-volume_low
volume_full = "\ufa7d" # nf-mdi-volume_high
volume_half = "\ufa7f" # nf-mdi-volume_medium
volume_muted = "\uf466" # nf-mdi-volume_mute
microphone_full = "\uf86b" # nf-mdi-microphone
microphone_half = "\uf86b" # nf-mdi-microphone
microphone_empty = "\uf86d" # nf-mdi-microphone_outline
microphone_muted = "\uf86c" # nf-mdi-microphone_off
weather_clouds = "\ufa8f" # nf-mdi-weather_cloudy
weather_default = "\ufa8f" # Cloud symbol as default
weather_rain = "\ufa95" # nf-mdi-weather_pouring
weather_snow = "\ufa97" # nf-mdi-weather_snowy
weather_sun = "\ufa98" # nf-mdi-weather_sunny
weather_thunder = "\ue31d" # nf-weather-thunderstorm
xrandr = "\uf879}" # nf-mdi-monitor_multiple
