#!/usr/bin/env fish
#
# Copyright (c) 2012, Jochen Issing <iss@nesono.com>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -ge NESONOBININSTALLATIONDIR
set --local FISHCONFIG ~/.config/fish/config.fish

# check, if login file exists
if test -e "$FISHCONFIG"
  echo "** Fish config file exists: $FISHCONFIG"
end

# add nesono-bin path to FISHCONFIG
if test -z "$NESONOBININSTALLATIONDIR"
  echo "** Adding nesono-bin path to $FISHCONFIG"
	echo -e "# the nesono script directory\nset -g NESONOBININSTALLATIONDIR '$SCRIPTDIR'\ntest -d '\$NESONOBININSTALLATIONDIR'; and set --universal fish_user_paths \$fish_user_paths \$NESONOBININSTALLATIONDIR" >> $FISHCONFIG

  echo "** Adding $SCRIPTDIR to current path"
  set --universal fish_user_paths $fish_user_paths $SCRIPTDIR
else
  echo "^^ nesono-bin already in path... not installing nesono-bin"
end


