#!/bin/bash

# function to create a directory and step into it
function cdmkdir()
{
  mkdir "$@"
  local path
  for path in "$@"; do
    # ignore any arguments
    if [[ "$path" = -* ]]; then :
    else
      cd "$path"
      return
    fi
  done
}

# function to create an absolute path from a relative one
function rel2abs()
{
  #echo "input: \"${1}\""
  # check, if argument is a file
  if [ -f "${1}" ]; then
    # directory name
    local dir="$(dirname "${1}")"
    #echo "dir: ${dir}"
    local file="$(basename "${1}")"
    #echo "file: ${file}"

    # change into dir
    pushd "${dir}" &> /dev/null
    local abspath="$(pwd)/${file}"
    echo "${abspath}"
    popd &> /dev/null
  fi
  if [ -d "${1}" ]; then
    # change into dir
    pushd "${1}" &> /dev/null
    local abspath="$(pwd)"
    echo "${abspath}"
    popd &> /dev/null
  fi

  return 0
}

# helper function to get the current users name (not using ${USER}, which could be corrupt)
function current_username()
{
  id | sed 's/uid=[0-9][0-9]*(\([a-zA-Z][a-zA-Z]*\)).*/\1/g'
}

# calculate something
function calc ()
{
  echo "$*" | bc -l
}

