#!/bin/bash

# the login file, we want to install the tools to
UNAME=`uname -s`
case ${UNAME} in
  "Linux")
    LOGINFILE=~/.bash_profile
    if [ ! -r ${LOGINFILE} ]; then
      LOGINFILE=~/.bashrc
    fi
  ;;
  "Darwin")
    LOGINFILE=~/.profile
  ;;
esac

# check, if login file exists
if [ -e "${LOGINFILE}" ]; then
  echo "sourcing login file: ${LOGINFILE}"
  # source login file and check, if we are already in path
  . ${LOGINFILE}
else
  echo "creating loginfile: ${LOGINFILE} (needs to sourced in login script)"
  touch ${LOGINFILE}
fi

# add nesono-bin path to LOGINFILE
if [ -z "${NESONOBASHRC}" ]; then
  echo "adding nesono-bin path to ${LOGINFILE}"
  cat >> ${LOGINFILE} <<-ENDOFSCRIPT
# the nesono script directory
if [ -d ~/nesono-bin ]; then
  export PATH=\${PATH}:~/nesono-bin
fi
ENDOFSCRIPT
  echo "adding nesono-bin to current path"
  export PATH=${PATH}:~/nesono-bin
else
  echo "nesono-bin already in path... not installing nesono-bin"
fi

# add BASHRC extensions to login file
if [ -z "${NESONOBASHRC}" ]; then
  echo "adding bashrc to file: ${LOGINFILE}"
  cat >> ${LOGINFILE} <<-ENDOFSCRIPT
# the nesono bash extension
if [ -f ~/nesono-bin/bashrc ]; then
  . ~/nesono-bin/bashrc
fi
ENDOFSCRIPT
else
  echo "NESONOBASHRC already set - not installing ${LOGINFILE}"
fi
